# Generated by Django 2.1 on 2018-11-29 16:06

from django.db import migrations, models
import django.db.models.deletion
import thecinemasource.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(storage=thecinemasource.storage_backends.MediaStorage(), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deprecated_id', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('IN', 'Interview')], default='IN', max_length=2)),
                ('excerpt', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='photograph',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.Post'),
        ),
    ]
