# Generated by Django 2.1 on 2018-09-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photograph',
            old_name='image',
            new_name='link',
        ),
    ]
