# Generated by Django 2.1 on 2018-11-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20181129_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deprecated_id',
            field=models.IntegerField(null=True),
        ),
    ]
