# Generated by Django 2.1 on 2018-11-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_auto_20181129_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
